### ISSUE TITLE
UI - Edit User Permissions

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [mcadamss1/STAGBAR#10]
Create UI for editing user permissions.

This can be done with a dynamically generated UI.
One row for each user found in the database, excluding the current user.
Each row should have a label for the username and 2 radio buttons, one for guest, one for administrator.
When the user hits ok, all changes should be saved to the database.
If the user hits cancel, go back to user management screen, save nothing.

**Comment by AnthonyWhitakerJr** [comment]
Incomplete - pushed to iteration 3.

**Comment by AnthonyWhitakerJr** [comment]
Any update on this issue???

**Comment by kansai2kansas** [comment]
Everything works 100% fine for this UI now. Closing this issue.
