### ISSUE TITLE
UI -Delete User

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [mcadamss1/STAGBAR#11]
Create UI to delete users.

This can be a panel with a check box for every user in the database, excluding the current user.
Put a label with suitable instructions at the top such as "Select user(s) to delete."
After the user selects the desired users to delete and clicks OK, a confirmation dialog such as the following should appear:

---

Are you sure you want to delete:  
 Bob    Susie   Joe  
 John   Alex  
 from the database?  
 Warning: this cannot be undone.  
                  OK     Cancel                  

---

OK on dialog deletes selected users.
Cancel on dialog returns to delete user page to alter selections.
Cancel on delete user page returns to user management screen.

**Comment by kansai2kansas** [comment]
Finished on Wednesday, 29th of March 2016

**Comment by AnthonyWhitakerJr** [comment]
Code does not compile. Please test.

**Comment by kansai2kansas** [comment]
So I've modified the code and it seems to compile just fine, but when I call this DeleteUserUI from main(), it keeps throwing NullPointerException. Since my code no longer throws any errors, I can't tell why it throws NPE from main(). Perhaps someone can have a look at my code? Thanks

**Comment by AnthonyWhitakerJr** [comment]
Incomplete - pushed to iteration 3.

**Comment by AnthonyWhitakerJr** [comment]
Any update on this issue???

**Comment by AnthonyWhitakerJr** [comment]
Looks like the current NPE is coming from the layout manager. About 5 seconds worth in Googling found this link: [http://stackoverflow.com/questions/9639017/intellij-gui-creator-jpanel-gives-runtime-null-pointer-exception-upon-adding-an](url)
Try to find a work-around.

**Comment by kansai2kansas** [comment]
After finishing my EditUserPermissionUI, I simply copy-pasted ALL of its methods to DeleteUserUI, changed the names of some variables, and voila! This issue is safe to close now.
