### ISSUE TITLE
UI - Change Password

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [mcadamss1/STAGBAR#12]
Create UI for changing passwords.

If a guest user clicks this button, they should see a screen requesting:

Old Password:
New Password:
Confirm New Password:

When the user clicks ok, save the new password to the database after validation.
UI should validate that old password matches the one in the database.
Also validate that new passwords match.
If any of this fails notify the user so they can fix it.

Cancel button should take them back to user management screen.

**Comment by kansai2kansas** [comment]
I finished this on Wednesday, 29th of March 2016

**Comment by AnthonyWhitakerJr** [comment]
Code does not compile. Please test.

**Comment by AnthonyWhitakerJr** [comment]
Tested with the database and this is functional. Congrats!

Things still needed:
*Margins around your 'contentPane' pane. 10 on all sides should do.
*Validation: When the old password is wrong, the username label is turned red & the username text field has focus.

**Comment by AnthonyWhitakerJr** [comment]
Also, if the current user is a guest, auto-fill the username field with the current user's username & disable that text field. Guests should not be able to change anyone else's password.

This can potentially wait until Iteration 3 as that is when we will be doing other disables based on permission level.

**Comment by kansai2kansas** [comment]
I've modified the oldPasswordField highlight and also added an If statement to verify whether or not "this" user is a Guest. I think this issue can be closed now
