### ISSUE TITLE
Database retrieve custom alcohol group names

### ISSUE THREAD

**Issue by mcadamss1** [mcadamss1/STAGBAR#35]
Need to retrieve the information of the custom alcohol groups.

**Comment by mcadamss1** [comment]
This issue is mostly done.  I did notice that a custom type of the same name can be stored in database.  I don't think this should be the case.  Any thoughts?

**Comment by AnthonyWhitakerJr** [comment]
Custom types should be unique by name & kind.
That is, we should not have two entries for Domestic & Bottled.
However, Domestic & Bottled and Domestic & Draft should be OK.
