### ISSUE TITLE
Use Case Model

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [mcadamss1/STAGBAR#45]
The final Use Case Model iteration documents the entire set of use cases with a use case context diagram (see the example in Figure 6.3 of the textbook), and fully dressed versions of all use cases using the template in Section 6.8 of the textbook.

**Comment by kansai2kansas** [comment]
Use Case Model for Iteration 3 is nearly identical to the Use Case Model in Iteration 2, except for the fact that this version also includes 6 brand new use cases that has been updated in Iteration 3: Create mixed drinks, Edit mixed drinks, Retire mixed drinks, Enter delivery, Change user password, and Retire alcohol.
