### ISSUE TITLE
System Sequence Diagrams

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [mcadamss1/STAGBAR#47]
Finalize system sequence diagrams (SSDs) for the relevant elements in the Domain Model, including at least one SSD for the basic flow of each use case selected for this iteration. There must be at least one SSD for an alternate flow of one of the selected use cases.

**Comment by kansai2kansas** [comment]
To avoid redundancy, I only add six brand new SSDs for use cases inside the Use Case Model that have been created in neither Iteration 1 nor Iteration 2.
